### ISSUE TITLE
Python files autogenerated ? 

### ISSUE THREAD

**Issue by VolkerH** [clEsperanto/pyclesperanto_prototype#17]
Hi Robert,

do you auto-generate the `.py` files in the plugins folder ?
If yes, I could not find the script, maybe you can give me a pointer.
In any case, it would be nice if the script would strip the semicolons from the line endings.

**Comment by haesleinhuepf** [comment]
Hey @VolkerH ,

no they're not. I just recently explained [here](https://github.com/clEsperanto/pyclesperanto_prototype/pull/14) why I think it's hard/complicated. Welcome in the loop 😉 

> In any case, it would be nice if the script would strip the semicolons from the line endings.

Yeah, that's my C++/Java brain putting semicolons at the end of everything; apologies;

**Comment by VolkerH** [comment]
sorry, I completely missed the overlap with the other issue there. I just remembered jni mentioning to me a while back that you were working on autogenerating the code. When I spotted the semicolons I thought I should look for the code generator and fix it.  Given that you are the code generator ....

**Comment by haesleinhuepf** [comment]
After some discussion with @tlambert03 and @jni - e.g. [here](https://github.com/clEsperanto/pyclesperanto_prototype/pull/14#issuecomment-659160602) I'm copying some issue-explanation + potential semi-solutions:

> I assume the effort will explode while doing it, because almost every single .py file is a special case IMHO. Let me explain:
> * The differences between the individual tier1.py files are tiny. Examples: If you want to crop an image, the global size of the OpenCL-kernel corresponds to the target image (output.shape) as it describes the size of the cropped region. In case of paste, the global size of the kernel comes from the input image size as it describes the size of the part to be inserted into the target image (src.shape).

> * Some .py files don't take care of image dimensionality. Others have to.

I recently experimented with filters which check for dimensionaly within the OpenCL code. Not sure yet if this can work in general. If so, that would allow us to process 2D images in YZ dimension. However, we would have to change many many opencl-kernels. [Example](https://github.com/clij/clijx/blob/master/src/main/java/net/haesleinhuepf/clijx/plugins/find_maxima_detect_maxima_x.cl#L49): If you want to check if an image has pixels in Z, one could:
```
if (get_global_size(2) > 1) {
```

> * There are separable filters and not-separable which are invoked quite differently.

> * Most kernels have input image size and output image size identical. In other cases they don't (trivial example: maximum-projection, complex example: histogram) Generation of output-image size belong in the python files, as its operation specific, I just haven't managed yet to find a good formalism. In Java it's this method which is implemented in all special cases and has default implementation for the others.

This issue might be solvable because we could specify in OpenCL, in a comment, which method to use to create the output. These different `create` methods could then be implemented in python, Java ,... I started [implementing them](https://github.com/clEsperanto/pyclesperanto_prototype/blob/af6da280fa5e6f4b1eb834e85383e10244728dc6/pyclesperanto_prototype/_tier0/create.py#L32).
