### ISSUE TITLE
3D image segmentation improvement 

### ISSUE THREAD

**Issue by skim245** [clEsperanto/pyclesperanto_prototype#223]
@haesleinhuepf thank you for all tremendous demo notebooks!

I've been following several demos to segment my 3D confocal images and 
"cle.voronoi_otsu_labeling" fails to segment some of my low quality images like example image below. 
[e.g.pdf](https://github.com/clEsperanto/pyclesperanto_prototype/files/9998922/e.g.pdf)

I've used top_hat background subtraction to reduce the background, but depending on the conditions, it still fails to segment some of my cells. 
any additional filtration suggestion would be great! 

and also have quick question on "distance_to_other_labels.ipynb" 
could we use this notebook tutorial to calculate the distance map between two channels? 
by calling label_image = channel 1 and sparse_label = channel 2 of our interest and extract the statistics of neighbors? 
thank you in advance!

**Comment by haesleinhuepf** [comment]
Hi @skim245 ,

thanks for the feedback! ♥️

> my low quality images like example image below.
> [e.g.pdf](https://github.com/clEsperanto/pyclesperanto_prototype/files/9998922/e.g.pdf)

If you share an example image, e.g. as TIF image, properly licensed, e.g. via https://zenodo.org, I would love to make an example notebook with your data!

> could we use this notebook tutorial to calculate the distance map between two channels?

I don't think so. How would you characterize a distance image between channels? I don't have a good idea of what that means.

Thanks again!

Best,
Robert

**Comment by skim245** [comment]
@haesleinhuepf  thank you for your offer! 
zenodo runs into erro for some reason, that i cannot upload image. i will try that again sometime later. 
but I kinda got around of getting better segmentation by adding more filters, like gaussian filters, and denoised using bilateral filters and adjusted image contrast and it seems doing a lot better!

and with my second question; let me elaborate a little more. 
After segmenting two channel images separately (like one from FITC and other from Cy5); 
if we merge these two images in a same plane, 
I was hoping that we could use the distance map to get co-local or neighborhood  (cells touching or being in a distance) information. can we add channel identity to each blobs and merge the image into one numpy array and calculate the distance? 
let me know if it doesn't make sense!

**Comment by thawn** [comment]
@skim245 _if we merge these two images in a same plane, I was hoping that we could use the distance map to get co-local or neighborhood (cells touching or being in a distance) information._

This is actually not trivial, because optical aberrations in the microscope work differently for different wavelengths of light. This means, that two color channels will be distorted differently and thus things that look like they are on the same pixel (e.g. the pixel with the coordinate 250, 240) in either channel, could actually be several hundred nanometers or even a few micron apart (depending on the quality of the optics and the imaging conditions). Therefore, if you want to do multi-color colocalization with better than a few µm accuracy, you need a reference (like fluorescent beads), that appears at the same position in both channels, to calibrate the colocalization. That being said, if you can characterize the error (by imaging beads under the same conditions) and can live with that error, then you are good to go. Otherwise, you need to prepare your sample with fluorescent beads to enable you to do an internal calibration.

**Comment by thawn** [comment]
@skim245 if you detect a significant difference in distance betwenn color channels and everything else is the same, you can certainly make qualitative statements. However, quantitative measurements will still be problematic. If possible, I would add fluorescent beads to the mounting medium for reference in future experiments.

**Comment by skim245** [comment]
@thawn i highly appreciate your comment! I will get beads and establish the internal calibration!

**Comment by thawn** [comment]
@skim245 you are very welcome 😄 good luck with the experiments!
