### ISSUE TITLE
Generated mesh doesn't correspond to adjacency matrix?

### ISSUE THREAD

**Issue by jo-mueller** [clEsperanto/pyclesperanto_prototype#269]
Hi @haesleinhuepf ,

I played a bit with the cle mesh/neighborhood functions (like in [this](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/demo/measurement/intensities_along_lines.ipynb) notebook) and I don't think I am using it correctly. Here's a MWE:

```python
import numpy as np
import pyclesperanto_prototype as cle
import napari

# make some random data
random_data = np.ones((200, 200))
for i in range(0, 200):
    random_data[i] *= i
coordinates = np.random.random((200, 2)) * 200

viewer = napari.Viewer()
viewer.add_image(random_data, name='random data')
viewer.add_points(coordinates, name='coordinates', size = 2, face_color='red')

# create an adjacency matrix
adjacency_matrix = np.zeros((len(coordinates), len(coordinates)))
adjacency_matrix[0, 1] = 1
adjacency_matrix[1, 2] = 1
adjacency_matrix[2, 3] = 1
adjacency_matrix[3, 4] = 1
adjacency_matrix[4, 5] = 1
adjacency_matrix = cle.symmetric_maximum_matrix(adjacency_matrix)

mesh = cle.create_like(random_data)
mesh = cle.touch_matrix_to_mesh(coordinates.T, adjacency_matrix, mesh)
viewer.add_image(mesh, name='mesh')

```

This gives me something like this:
![capture](https://user-images.githubusercontent.com/38459088/221648876-931433c3-d8c6-4406-8c3a-c11778624241.png)

What irritates me a bit is that the node positions in the mesh image are quite far off the node positions. In particular, it's more than single pixels so it also doesn't seem to be an integer/floating point conversion thing.

Do you have an idea about what I am doing wrong? Thanks in advance!

*Edit*: Fixed MWE error.

**Comment by jo-mueller** [comment]
Hi @haesleinhuepf ,

sorry - fixed it above. The `random_data` variable also isn't really used in this example. I created it to play with the `generate_mean_intensity_between_points_matrix` function but found that I probably didn't use cle's connection matrix syntax properly in the first place.

**Comment by haesleinhuepf** [comment]
Awesome, thanks @jo-mueller ! I think the reason is that clesperanto assumes coordinates in the coordinate list in format `[x,y]` and napari assumes `[y,x]`. Clesperanto comes from Java island, that's why ;-). Some more comments:

* The adjacency matrices in clesperanto are one element larger than number of points, because the first row/column corresponds to background. Background does not have a coordinate. In case of label images, the label with `ID 1` corresponds to the row/colum `[1]` in the adjacency matrix.
```
adjacency_matrix = np.zeros((len(coordinates) + 1, len(coordinates) + 1))
```

* This line makes a point touch the backround (be neighbor of background). This line will not be drawn. The background has no coordinate.
```
adjacency_matrix[0, 1] = 1
```

* You can convert `y,x` coordinates into `x,y` coordinates using `[::-1]`:
```
mesh = cle.touch_matrix_to_mesh(coordinates.T[::-1], adjacency_matrix, mesh)
```

* Add the layer to the viewer using the following command to make points and lines visible at the same time:
```
viewer.add_image(mesh, name='mesh', blending='additive')
```

This is how the result looks:
![image](https://user-images.githubusercontent.com/12660498/221830237-5d6d58b0-0991-4b98-a146-89e8dbcd8b9e.png)


And that's the complete code:
```
import numpy as np
import pyclesperanto_prototype as cle
import napari

# make some random data
random_data = np.ones((200, 200))
for i in range(0, 200):
    random_data[i] *= i
coordinates = np.random.random((200, 2)) * 200

viewer = napari.Viewer()
viewer.add_image(random_data, name='random data')
viewer.add_points(coordinates, name='coordinates', size = 5, face_color='red')

# create an adjacency matrix
adjacency_matrix = np.zeros((len(coordinates) + 1, len(coordinates) + 1))
adjacency_matrix[0, 1] = 1
adjacency_matrix[1, 2] = 1
adjacency_matrix[2, 3] = 1
adjacency_matrix[3, 4] = 1
adjacency_matrix[4, 5] = 1
adjacency_matrix = cle.symmetric_maximum_matrix(adjacency_matrix)

mesh = cle.create_like(random_data)
mesh = cle.touch_matrix_to_mesh(coordinates.T[::-1], adjacency_matrix, mesh)
viewer.add_image(mesh, name='mesh', blending='additive')
```

Let me know if there are open questions!

**Comment by haesleinhuepf** [comment]
Thanks for your feedback @jo-mueller . Feel free to reopen the issue in case your problem is not solved.

**Comment by jo-mueller** [comment]
Absolutely fine, thanks for the help!
