### ISSUE TITLE
x and y **minimum position** projections

### ISSUE THREAD

**Issue by ClementCaporal** [clEsperanto/pyclesperanto_prototype#272]
Hello,

Thank you for your work.
I would like to get the *x* and *y* minimum projection positions (`x_position_of_minimum_x_projection`) and (`y_position_of_minimum_y_projection`).

If I understand correctly it only exists for the z axis (`z_position_of_minimum_z_projection`)
https://github.com/clEsperanto/pyclesperanto_prototype/blob/006379e7302cc0f76a571b5cdf3fb3962c9461c9/pyclesperanto_prototype/_tier2/__init__.py#L63

Is there a reason these functions doesn't exist for x and y?

Currently my workaround uses the maximum position on my negative matrix. Maybe not ideal.
 https://github.com/clEsperanto/pyclesperanto_prototype/blob/006379e7302cc0f76a571b5cdf3fb3962c9461c9/pyclesperanto_prototype/_tier2/__init__.py#L57

**Comment by haesleinhuepf** [comment]
No big reason behind actually. I'd assume one could easily implement them using `transpose_xz` and `z_position_of_minimum_z_projection`... And if it turns out that this approach is super slow, we could still implement a custom open-cl kernel.

Would you be interested in contributing and sending a pull-request @ClementCaporal ?

**Comment by haesleinhuepf** [comment]
done in #277
