### ISSUE TITLE
Test failure on Linux (CI) potentially related to OpenCL driver version?

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto_prototype#28]
The current failure in the CI/linux mentions this issue:

```
self = <pyopencl._cl.Kernel object at 0x7fddfe3f4950>
queue = <pyopencl._cl.CommandQueue object at 0x7fde0a47fdd0>
global_size = (10, 1), local_size = None
arg0 = <pyopencl._cl.Buffer object at 0x7fddfe85def0>, arg1 = array([0])
arg2 = array([0.], dtype=float32), global_offset = None, g_times_l = None
allow_empty_ndrange = False, wait_for = None

>   ???
E   pyopencl._cl.LogicError: when processing argument #2 (1-based): clSetKernelArg failed: INVALID_ARG_SIZE
```

I suspect that changing [this line](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/pyclesperanto_prototype/_tier0/execute.py#L114):
```
arguments.append(np.array([value], np.float32))
```
 
to this line:
```
arguments.append(np.array([value]))
```

could fix the issue. Unfortunately, tests fail then on my Windows system. I'll try later this week on my Linux machine. Just wanted to raise the point: There might be two different strategies for fixing this:
* Build in a switch which executes either the one or the other line depending on operating system / driver / version / ....
* Change the driver used in the CI?

Cheers,
Robert

**Comment by tlambert03** [comment]
I haven't looked closely yet... do you know what changed between the [working tests](https://github.com/clEsperanto/pyclesperanto_prototype/actions/runs/172892676) and the [failing test](https://github.com/clEsperanto/pyclesperanto_prototype/actions/runs/172904432)?  Is this a new kernel?  or a modification of the code and/or tests that were previously working?  The fact that it was working before suggests that the driver isn't totally bonked right?  Or did new features get added that might require a different driver?

**Comment by haesleinhuepf** [comment]
> I haven't looked closely yet... do you know what changed between the [working tests](https://github.com/clEsperanto/pyclesperanto_prototype/actions/runs/172892676) and the [failing test](https://github.com/clEsperanto/pyclesperanto_prototype/actions/runs/172904432)?

So from working to failing there was a more serious issue: I screwed up the `create` method which affected many tests. And I added a new [kernel](https://github.com/clEsperanto/pyclesperanto_prototype/blob/d2728eb11422aa4fd09f112b9581a3a40f3066f3/tests/test_touch_matrix_to_mesh.py), which caused issues as well.

At the moment, quite some [tests fail](https://github.com/clEsperanto/pyclesperanto_prototype/runs/889348459). What they have in common is, they [take an integer](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/tests/test_copy_slice.py#L22) as parameter. Then, it reports [these parameters](https://github.com/clEsperanto/pyclesperanto_prototype/runs/889348459#step:7:279):
```
arg0 = <pyopencl._cl.Buffer object at 0x7f78f547b650>
arg1 = <pyopencl._cl.Buffer object at 0x7f78f5ceb6b0>, arg2 = array([0])
```
And this error:
```
pyopencl._cl.LogicError: clSetKernelArg failed: INVALID_ARG_SIZE
```

Again, that's related to the lines [here](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/pyclesperanto_prototype/_tier0/_execute.py#L111-L114). 

I assume the tests also run through on your mac?

**Comment by tlambert03** [comment]
> I assume the tests also run through on your mac?

Everything is executing correctly on my mac, but these four tests fail the `np.allclose` test:
```
FAILED tests/test_nonzero_maximum_box.py::test_nonzero_maximum_box
FAILED tests/test_nonzero_maximum_diamond.py::test_nonzero_maximum_diamond
FAILED tests/test_nonzero_minimum_box.py::test_nonzero_minimum_box
FAILED tests/test_nonzero_minimum_diamond.py::test_nonzero_minimum_diamond
```

> And I added a new kernel, which caused issues as well.

Ah.  Ok well that's a "good" problem :) gotta add kernels!  Here's one strategy for "kicking the can down the road" a bit.  Because it can be so useful to have generally passing tests on CI (so that as you work on many different PRs you can quickly see if the current PR has broken any existing functionality), and because I definitely expect that we'll run into many platform-specific issues here... I think we should make liberal use of [`pytest.mark.xfail`](https://docs.pytest.org/en/latest/skipping.html), which lets you say "I expect this test to currently fail, in these conditions, with this specific exception":

See for instance what I did in [test_maximum_sphere](https://github.com/clEsperanto/pyclesperanto_prototype/blob/0fffcbfbc48b3b29334d6cff1c1173f524342c7d/tests/test_maximum_sphere.py):

https://github.com/clEsperanto/pyclesperanto_prototype/blob/0fffcbfbc48b3b29334d6cff1c1173f524342c7d/tests/test_maximum_sphere.py#L4-L10

The first string (`'LINUX and CI'`) specifies the conditions under which this test is "allowed" to fail.  So that you might have it working locally (`not CI`) but not on CI, but you're "ok" with that for now.  The `raises=cl.LogicError` part says exactly what exception you expect... and a nice trick is to use the [`strict=True` xfail option](https://docs.pytest.org/en/latest/skipping.html#strict-parameter), which will actually _fail_ the test if it "passes" (unexpectedly).  This lets you just run tests while trying to fix your code, and if you get a test failure it means you fixed it (at which point you remove the xfail mark).

So if you want to mark the 7 remaining tests that are failing, we can get our CI working again so that as we work on other features we can see if we've broken new things, or if it's just the "expected" bugs
